In [3]:
import pandas as pd

df = pd.read_csv('Final Data (1).csv')

In [4]:
print(df.shape)

(3840, 405)


In [5]:
df.head(20)

Image  Gender  Mean of Pen Pressure  \
0   AHTD3A0001_Para1.tif       1            249.134614   
1   AHTD3A0001_Para2.tif       1            250.077084   
2   AHTD3A0001_Para3.tif       1            247.620429   
3   AHTD3A0001_Para4.tif       1            248.839932   
4   AHTD3A0002_Para1.tif       1            247.646814   
5   AHTD3A0002_Para2.tif       1            252.164383   
6   AHTD3A0002_Para3.tif       1            248.486903   
7   AHTD3A0002_Para4.tif       1            249.605460   
8   AHTD3A0003_Para1.tif       1            246.493255   
9   AHTD3A0003_Para2.tif       1            251.476216   
10  AHTD3A0003_Para3.tif       1            244.409855   
11  AHTD3A0003_Para4.tif       1            252.445700   
12  AHTD3A0004_Para1.tif       1            245.672449   
13  AHTD3A0004_Para2.tif       1            250.181454   
14  AHTD3A0004_Para3.tif       1            244.754924   
15  AHTD3A0004_Para4.tif       1            250.548098   
16  AHTD3A0005_Para1.tif       1            246.412320   
17  AHTD3A0005_Para2.tif       1            247.196250   
18  AHTD3A0005_Para3.tif       1            247.037536   
19  AHTD3A0005_Para4.tif       1            248.481183   

    Standard Deviation of Pen Pressure  Writing Irregularity  Left_Margin_1  \
0                            22.344913            612.000000           1809   
1                            20.707856           1275.000000           1532   
2                            25.797931           4143.750000           1071   
3                            23.681196           2754.000000            507   
4                            26.984456          14498.571430            185   
5                            16.629123           6593.571429           2169   
6                            25.216157          10869.375000           1056   
7                            22.985151           5496.666667           1074   
8                            31.774714          10863.000000           2193   
9                            20.137314            765.000000           1409   
10                           34.348653              0.000000            179   
11                           17.117555              0.000000            891   
12                           32.184809          37803.750000           2045   
13                           23.645119           1530.000000            717   
14                           35.208419           4675.000000            288   
15                           23.225350           3315.000000           2174   
16                           30.432260          26574.642860           2221   
17                           29.139114          34892.500000           1499   
18                           29.044132          16218.000000           2049   
19                           26.436650          26838.750000           1881   

    Left_Margin_2  Left_Margin_3  Left_Margin_4  Left_Margin_5  ...  \
0            1809            452            452            452  ...   
1            1530           1530            439            436  ...   
2            1071           1069           1067           1066  ...   
3             506            506            506            506  ...   
4             185            185            185            186  ...   
5            1961           1959            409            406  ...   
6            1055            166            164            164  ...   
7            1074           1845           1845           1845  ...   
8            2189           2189           2190           2193  ...   
9            1403           1400           1400           1398  ...   
10            178            178            178            179  ...   
11            891            797            512            511  ...   
12           2044           2043            912            912  ...   
13            717            717           2200           2200  ...   
14            288            288            288            289  ...   
15  

In [6]:
df.isnull().sum()

Image                                   0
Gender                                  0
Mean of Pen Pressure                    0
Standard Deviation of Pen Pressure      0
Writing Irregularity                  156
                                     ... 
Right_Margin_196                        0
Right_Margin_197                        0
Right_Margin_198                        0
Right_Margin_199                        0
Right_Margin_200                        0
Length: 405, dtype: int64

In [7]:
df.dropna(inplace=True)
df.to_csv('Final Data_Cleaned.csv')

In [8]:
y = df['Gender'].to_numpy()
X = df.drop(columns=['Gender']).to_numpy()

In [9]:
X

array([['AHTD3A0001_Para1.tif', 249.1346142, 22.34491297, ..., 388, 390,
        392],
       ['AHTD3A0001_Para2.tif', 250.0770841, 20.70785589, ..., 79, 88,
        103],
       ['AHTD3A0001_Para3.tif', 247.620429, 25.79793146, ..., 18, 20, 22],
       ...,
       ['AHTD3A1181_Para2.tif', 251.1954594, 20.59451247, ..., 534, 536,
        539],
       ['AHTD3A1181_Para3.tif', 251.1986442, 20.7897829, ..., 52, 52, 52],
       ['AHTD3A1181_Para4.tif', 248.9149903, 25.57150298, ..., 71, 71,
        70]], dtype=object)

In [10]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [11]:
from sklearn.preprocessing import MinMaxScaler
filenames = X[:, 0]
numeric_data = X[:, 1:]
scaler = MinMaxScaler()
X = scaler.fit_transform(numeric_data)

In [12]:
X

array([[0.77657622, 0.25548289, 0.00385852, ..., 0.15718928, 0.15800162,
        0.16217337],
       [0.81985486, 0.22366279, 0.00803859, ..., 0.03168156, 0.03533712,
        0.0423061 ],
       [0.70704415, 0.32260052, 0.0261254 , ..., 0.00690496, 0.0077173 ,
        0.00871008],
       ...,
       [0.87121115, 0.22145969, 0.        , ..., 0.21649066, 0.21730301,
        0.22314392],
       [0.8713574 , 0.22525523, 0.00241158, ..., 0.02071487, 0.02071487,
        0.02115305],
       [0.76649099, 0.31819934, 0.01527331, ..., 0.02843217, 0.02843217,
        0.02861883]])

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [28]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth = 8)
clf.fit(X_train,y_train)
y_predict = clf.predict(X_test)

In [29]:
y_predict

array([1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,

In [30]:
y_test

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,

In [31]:
clf.score(X_test, y_test)

0.6322930800542741

In [32]:
clf.score(X_train, y_train)

0.8126908720732948

In [33]:
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, precision_recall_fscore_support, classification_report

f1_score(y_test, y_predict)

0.7411652340019103

In [34]:
confusion_matrix(y_test, y_predict)

array([[ 78, 166],
       [105, 388]], dtype=int64)

In [35]:
accuracy_score(y_test, y_predict)

0.6322930800542741

In [36]:
precision_recall_fscore_support(y_test, y_predict)

(array([0.42622951, 0.70036101]),
 array([0.31967213, 0.78701826]),
 array([0.36533958, 0.74116523]),
 array([244, 493], dtype=int64))

In [37]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.43      0.32      0.37       244
           1       0.70      0.79      0.74       493

    accuracy                           0.63       737
   macro avg       0.56      0.55      0.55       737
weighted avg       0.61      0.63      0.62       737



In [24]:
clf.tree_

In [25]:
from sklearn import tree

tree.plot_tree(clf)

[Text(0.5469437847544022, 0.9615384615384616, 'x[208] <= 0.203\ngini = 0.456\nsamples = 2947\nvalue = [1034, 1913]'),
 Text(0.24948592446709916, 0.8846153846153846, 'x[11] <= 0.444\ngini = 0.41\nsamples = 1789\nvalue = [514, 1275]'),
 Text(0.1650689295644115, 0.8076923076923077, 'x[269] <= 0.079\ngini = 0.451\nsamples = 920\nvalue = [316, 604]'),
 Text(0.12022126969416126, 0.7307692307692307, 'x[371] <= 0.22\ngini = 0.424\nsamples = 717\nvalue = [219, 498]'),
 Text(0.09864457831325302, 0.6538461538461539, 'x[124] <= 0.937\ngini = 0.409\nsamples = 679\nvalue = [195, 484]'),
 Text(0.083758109360519, 0.5769230769230769, 'x[267] <= 0.101\ngini = 0.401\nsamples = 667\nvalue = [185, 482]'),
 Text(0.06510658016682114, 0.5, 'x[204] <= 0.017\ngini = 0.394\nsamples = 659\nvalue = [178, 481]'),
 Text(0.03892493049119555, 0.4230769230769231, 'x[206] <= 0.117\ngini = 0.262\nsamples = 155\nvalue = [24, 131]'),
 Text(0.03151065801668211, 0.34615384615384615, 'x[382] <= 0.305\ngini = 0.216\nsamples = 

In [26]:
from sklearn.model_selection import cross_validate

results = cross_validate(clf, X, y, cv=4, return_train_score =  True, scoring=('accuracy','f1','recall','precision','roc_auc'))
results

{'fit_time': array([1.88117838, 1.86230659, 1.9327457 , 2.00007653]),
 'score_time': array([0.02297163, 0.00797796, 0.00798988, 0.00957012]),
 'test_accuracy': array([0.52008686, 0.60694897, 0.57980456, 0.57437568]),
 'train_accuracy': array([0.93340572, 0.85269634, 0.93412957, 0.96453131]),
 'test_f1': array([0.62981575, 0.7211094 , 0.68459658, 0.69278997]),
 'train_f1': array([0.95061728, 0.896464  , 0.9512848 , 0.97316539]),
 'test_recall': array([0.62458472, 0.77740864, 0.69883527, 0.73544093]),
 'train_recall': array([0.98170732, 0.9767184 , 0.98448753, 0.98448753]),
 'test_precision': array([0.63513514, 0.67241379, 0.67092652, 0.65481481]),
 'train_precision': array([0.921436  , 0.8283968 , 0.92024858, 0.9621007 ]),
 'test_roc_auc': array([0.48840854, 0.48671357, 0.51847442, 0.52452163]),
 'train_roc_auc': array([0.97587594, 0.90742476, 0.97122323, 0.98591971])}

In [27]:
results['test_accuracy']

array([0.52008686, 0.60694897, 0.57980456, 0.57437568])